# Generated by Django 5.2.7 on 2025-10-17 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+256712345678' or '0712345678'", regex='^(\\+?256|0)?[0-9]{9}$')]),
        ),
    ]
